name: Upgrade Requirements

on:
  schedule:
    # will start the job at 3 every monday (UTC)
    - cron: "0 3 * * 1"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: 'master'

jobs:
  upgrade_requirements:

    with:
      branch: ${{ github.event.inputs.branch }}
      team_reviewers: "arbi_bom"
      email_address: "arbi-bom@edx.org"
      send_success_notification: false
    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master
